# Generated by Django 5.0.4 on 2024-05-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.IntegerField()),
                ('file', models.FileField(upload_to='songs/')),
            ],
            options={
                'db_table': 'songs',
            },
        ),
    ]
