# Generated by Django 5.0.4 on 2024-05-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_song_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(default='kaiju8', max_length=200),
            preserve_default=False,
        ),
    ]
